//------------------------------------------------------------------------------
// <auto-generated>
//     Copyright (c) Study Now. Все права защищены.
//     Автор: Бикеев Адиль Иссаевич.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyNowMobileApp.ViewModels.Course
{
    using System;
    using System.Collections.Generic;
    using StudyNowMobileApp.Localization;
    using StudyNowMobileApp.Models.CoursesList;
    using StudyNowMobileApp.Models.Tools;
    using StudyNowMobileApp.Views.ToolsMenu;

    /// <summary>
    /// Служит прослойкой для CoursesListPage.xaml.
    /// </summary>
    public class CoursesListViewModel : BaseViewModel
    {
        /// <summary>
        /// Gets or sets список курсов.
        /// </summary>
        public IList<CoursesListModel> Courses { get; private set; }

        /// <summary>
        /// Gets or sets дейсвтия при выборе курса.
        /// </summary>
        public CoursesListModel SelectedToolCommand
        {
            get => null;
            set
            {
                if (value != null)
                {
                    this.Navigation.PushAsync(value.TypePage);
                    this.UpdatePropertyChanged();
                }
            }
        }

        /// <inheritdoc/>
        public override string TitlePage => LocalizedText.CoursesListPageTitle;

        /// <summary>
        /// Initializes a new instance of the <see cref="CoursesListViewModel"/> class.
        /// </summary>
#pragma warning disable SA1201 // Elements should appear in the correct order
        public CoursesListViewModel(IList<CoursesListModel> coursesLists)
#pragma warning restore SA1201 // Elements should appear in the correct order
        {
            this.Courses = coursesLists;
        }

        /// <inheritdoc/>
        protected override List<string> PropertyNames => new List<string>()
        {
            nameof(this.TitlePage),
            nameof(this.Courses),
        };
    }
}
