//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.ViewModels.Course
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Input;
    using StudyNowMobileApp.Localization;
    using StudyNowMobileApp.Models.CoursesList;
    using StudyNowMobileApp.Models.Tools;
    using StudyNowMobileApp.Views.Course;
    using StudyNowMobileApp.Views.ToolsMenu;
    using Xamarin.Forms;

    /// <summary>
    /// Служит прослойкой для CoursesListPage.xaml.
    /// </summary>
    public class CoursesListViewModel : BaseViewModel
    {
        /// <summary>
        /// Gets or sets список курсов.
        /// </summary>
        public IList<CoursesListModel> Courses { get; private set; }

        /// <summary>
        /// Gets or sets действия при выборе курса.
        /// </summary>
        public ICommand SelectedCourseCommand { get; private set; }

        /// <summary>
        /// Переходит на страницу курса.
        /// </summary>
        /// <param name="coursName">Название выбранного курса.</param>
        private void SelectedCourse(string coursName)
        {
            var cours = this.Courses.First(x => x.DisplayName == coursName);
            this.Navigation.PushAsync(new SelectedCours(cours));
            this.UpdatePropertyChanged();
        }

        /// <inheritdoc/>
        public override string TitlePage => LocalizedText.CoursesListPageTitle;

        /// <summary>
        /// Initializes a new instance of the <see cref="CoursesListViewModel"/> class.
        /// </summary>
        public CoursesListViewModel(IList<CoursesListModel> coursesLists)
        {
            this.Courses = coursesLists;
            this.SelectedCourseCommand = new Command<string>(this.SelectedCourse);
        }

        /// <inheritdoc/>
        protected override List<string> PropertyNames => new List<string>()
        {
            nameof(this.TitlePage),
            nameof(this.Courses),
        };
    }
}
