//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.Models.CoursesList
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Xamarin.Forms;

    /// <summary>
    /// Кнопка курса на странице CourseListPage.xaml.
    /// </summary>
    public class CourseModel
    {
        /// <summary>
        /// Gets or sets имя картинки устанавливаемая в качестве иконки.
        /// </summary>
        public string IconImage { get; set; }

        /// <summary>
        /// Фоновая картинка устанавливаемая на странице курса.
        /// </summary>
        public string BacgroundCoursImage { get; set; }

        /// <summary>
        /// Gets or sets имя курса.
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets страницы с выполнением заданий.
        /// </summary>
        public IList<ContentPage> TaskPages { get; set; }
    }
}