//------------------------------------------------------------------------------
// <auto-generated>
//     Copyright (c) Study Now. Все права защищены.
//     Автор: Бикеев Адиль Иссаевич.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyNowMobileApp.Views.Main
{
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;

    /// <summary>
    /// Страница "Статистика".
    /// </summary>
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Stats : ContentPage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Stats"/> class.
        /// </summary>
        public Stats()
        {
            this.InitializeComponent();
        }
    }
}