//------------------------------------------------------------------------------
// <auto-generated>
//     Copyright (c) Study Now. Все права защищены.
//     Автор: Бикеев Адиль Иссаевич.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyNowMobileApp.Views.Main
{
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;

    /// <summary>
    /// Странциа "Тренироваться".
    /// </summary>
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class Workout : ContentPage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Workout"/> class.
        /// </summary>
        public Workout()
        {
            this.InitializeComponent();
        }
    }
}