//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.ViewModels.Main
{
    using System;
    using System.Collections.Generic;
    using StudyNowMobileApp.Localization;

    /// <summary>
    /// Главная страница приложения.
    /// </summary>
    public class MainViewModel : BaseViewModel
    {
        /// <summary>
        /// Gets or sets описание кнопки "Домой" на навигационной панели.
        /// </summary>
        public string HomeTitle
        {
            get => LocalizedText.HomeIconTitle;
            set => throw new NotImplementedException();
        }

        /// <summary>
        /// Gets or sets описание кнопки "Тренироваться" на навигационной панели.
        /// </summary>
        public string WorkoutTitle
        {
            get => LocalizedText.WorkoutIconTitle;
            set => throw new NotImplementedException();
        }

        /// <summary>
        /// Gets or sets описание кнопки "Тренироваться" на навигационной панели.
        /// </summary>
        public string NewsTitle
        {
            get => LocalizedText.NewsIconTitle;
            set => throw new NotImplementedException();
        }

        /// <summary>
        /// Gets or sets описание кнопки "Статистика" на навигационной панели.
        /// </summary>
        public string StatsTitle
        {
            get => LocalizedText.StatsIconTitle;
            set => throw new NotImplementedException();
        }

        /// <inheritdoc/>
        public override string TitlePage => LocalizedText.HomeIconTitle;

        /// <inheritdoc/>
        protected override List<string> PropertyNames => new List<string>()
        {
            nameof(this.HomeTitle),
            nameof(this.WorkoutTitle),
            nameof(this.NewsTitle),
            nameof(this.StatsTitle),
        };
    }
}
