//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.Models.Course
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// Задание курса.
    /// </summary>
    public class CourseTask
    {
        /// <summary>
        /// Gets or sets Название задания для оторажения на странице курса.
        /// </summary>
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets полное название заадния.
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether, задание выполненым.
        /// </summary>
        public bool IsDone { get; set; }

        /// <summary>
        /// Gets картинку показывающая, что задание выполнено/нет в зависимости от статуса IsDone.
        /// </summary>
        public string CheckIcon => this.IsDone ? this.CheckOnIcon : this.CheckOffIcon;

        /// <summary>
        /// Gets or sets иконка, показывающая, что задание выполнено.
        /// </summary>
        public string CheckOnIcon { get; set; }

        /// <summary>
        /// Gets or sets иконка, показывающая, что задание не выполнено.
        /// </summary>
        public string CheckOffIcon { get; set; }
    }
}
