//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.Hellpers
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Text;
    using StudyNowMobileApp.Localization;
    using StudyNowMobileApp.Models.Tools;
    using StudyNowMobileApp.Views.ToolsMenu;

    /// <summary>
    /// Класс-помощник в локализации приложения.
    /// </summary>
    public static class LocalizationHellper
    {
        /// <summary>
        /// Gets список языков.
        /// </summary>
        public static List<Language> Languages => new List<Language>()
        {
            new Language() { DisplayName = LocalizedText.LabelLangRuText, ShortName = "ru-RU", ImageSource = "Tools_Lang_Russian.png" },
            new Language() { DisplayName = LocalizedText.LabelLangEnText, ShortName = "en-GB", ImageSource = "Tools_Lang_English.png" },
        };

        private static Language DefaultLang => Languages.First();

        /// <summary>
        /// Устанавливает локализацию приложения.
        /// </summary>
        /// <param name="lang">Язык приложения.</param>
        public static void SetLocalization(Language lang)
        {
            CultureInfo.CurrentCulture = new CultureInfo(lang?.ShortName);
            CultureInfo.CurrentUICulture = CultureInfo.CurrentCulture;
            LocalizedText.Culture = CultureInfo.CurrentCulture;
        }

        /// <summary>
        /// Устанавливает локализацию приложения, если есть  соответствующий ему короткое имя в Languages.
        /// В ином случаи задает язык по умолчанию.
        /// </summary>
        /// <param name="lang">Короткое название языка.</param>
        public static void SetLocalizationOrDefault(string lang)
        {
            Language language = DefaultLang;

            foreach (var item in Languages)
            {
                if (item.ShortName == lang)
                {
                    language = item;
                    break;
                }
            }

            SetLocalization(language);
        }
    }
}
