//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.ViewModels.Tools
{
    using System;
    using System.Collections.Generic;
    using StudyNowMobileApp.Localization;
    using StudyNowMobileApp.Models.Tools;
    using StudyNowMobileApp.Views.ToolsMenu;

    /// <summary>
    /// Служит прослойкой для Tools.xaml.
    /// </summary>
    public class ToolsViewModel : BaseViewModel
    {
        /// <summary>
        /// Gets список настроек приложения.
        /// </summary>
        public List<Tool> Tools => new List<Tool>()
        {
            new Tool() { Name = LocalizedText.ToolsLanguageTitle, TypePage = new LanguageTools(this) },
        };

        /// <summary>
        /// Gets or sets дейсвтия при выборе настройки.
        /// </summary>
        public Tool SelectedToolCommand
        {
            get => null;
            set
            {
                if (value != null)
                {
                    this.Navigation.PushAsync(value.TypePage);
                    this.UpdatePropertyChanged();
                }
            }
        }

        /// <inheritdoc/>
        public override string TitlePage => LocalizedText.ToolsPageTitle;

        /// <summary>
        /// Initializes a new instance of the <see cref="ToolsViewModel"/> class.
        /// </summary>
#pragma warning disable SA1201 // Elements should appear in the correct order
        public ToolsViewModel()
#pragma warning restore SA1201 // Elements should appear in the correct order
        {
        }

        /// <inheritdoc/>
        protected override List<string> PropertyNames => new List<string>()
        {
            nameof(this.TitlePage),
            nameof(this.Tools),
        };
    }
}
