//------------------------------------------------------------------------------
// <auto-generated>
// MIT License
// 
// Copyright (c) 2020 Bikeev Adil Issaevich
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
// </auto-generated>
//------------------------------------------------------------------------------
namespace StudyNowMobileApp.Views.Course
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;
    using StudyNowMobileApp.Models.CoursesList;
    using StudyNowMobileApp.ViewModels;
    using StudyNowMobileApp.ViewModels.Course;
    using StudyNowMobileApp.Views.BaseView;
    using Xamarin.Forms;
    using Xamarin.Forms.Xaml;

    /// <summary>
    /// Список курсов.
    /// </summary>
    [XamlCompilation(XamlCompilationOptions.Compile)]
    public partial class CoursesListPage : BaseContentPage
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CoursesListPage"/> class.
        /// </summary>
        /// <param name="coursesLists">Список курсов для отображения на странице.</param>
        public CoursesListPage(IList<CoursesListModel> coursesLists)
        {
            this.InitializeComponent();
            this.BindingContext = new CoursesListViewModel(coursesLists) { Navigation = this.Navigation };
        }
    }
}