name: CI on Push and Pull Request

on: 
  branches:
    - master   # Push events on master branch
    - develop  # Push events on develop branch
  push:
    tags:
    - '*'

jobs:
  Practice:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Show what in there
      run: |
        ls
    - name: Show what it's inside
      run: |
        cd ..
        ls
  Android:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: Android
      run: |
        cd StudyNowMobileApp
        nuget restore
        cd StudyNowMobileApp.Android
        msbuild StudyNowMobileApp.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
  iOS:

    runs-on: macos-latest
    
    steps:

    - uses: actions/checkout@v1
      
    - name: iOS
      run: |
        cd StudyNowMobileApp
        nuget restore
        msbuild StudyNowMobileApp.iOS/StudyNowMobileApp.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhoneSimulator /p:Configuration=Debug
